TRAIN_FILENAME = "train.csv"
TEST_FILENAME = "test.csv"
USER_DATA_FILENAME = "users.csv"
BOOK_DATA_FILENAME = "books.csv"
BOOK_GENRES_FILENAME = "book_genres.csv"
GENRES_FILENAME = "genres.csv"
BOOK_DESCRIPTIONS_FILENAME = "book_descriptions.csv"
SUBMISSION_FILENAME = "submission.csv"
TFIDF_VECTORIZER_FILENAME = "tfidf_vectorizer.pkl"
BERT_EMBEDDINGS_FILENAME = "bert_embeddings.pkl"
BERT_MODEL_NAME = "DeepPavlov/rubert-base-cased"
PROCESSED_DATA_FILENAME = "processed_features.parquet"

COL_USER_ID = "user_id"
COL_BOOK_ID = "book_id"
COL_TARGET = "rating"
COL_SOURCE = "source"
COL_PREDICTION = "rating_predict"
COL_HAS_READ = "has_read"
COL_TIMESTAMP = "timestamp"

F_USER_MEAN_RATING = "user_mean_rating"
F_USER_RATINGS_COUNT = "user_ratings_count"
F_BOOK_MEAN_RATING = "book_mean_rating"
F_BOOK_RATINGS_COUNT = "book_ratings_count"
F_AUTHOR_MEAN_RATING = "author_mean_rating"
F_BOOK_GENRES_COUNT = "book_genres_count"

COL_GENDER = "gender"
COL_AGE = "age"
COL_AUTHOR_ID = "author_id"
COL_PUBLICATION_YEAR = "publication_year"
COL_LANGUAGE = "language"
COL_PUBLISHER = "publisher"
COL_AVG_RATING = "avg_rating"
COL_GENRE_ID = "genre_id"
COL_DESCRIPTION = "description"

VAL_SOURCE_TRAIN = "train"
VAL_SOURCE_TEST = "test"

MISSING_CAT_VALUE = "-1"
MISSING_NUM_VALUE = -1
PREDICTION_MIN_VALUE = 0
PREDICTION_MAX_VALUE = 10

F_USER_BOOKS_READ = "user_books_read"
F_USER_TOTAL_INTERACTIONS = "user_total_interactions"
F_USER_READ_RATIO = "user_read_ratio"
F_USER_DAYS_TO_READ_MEAN = "user_days_to_read_mean"
F_USER_DAYS_TO_READ_MEDIAN = "user_days_to_read_median"
F_USER_DAYS_TO_READ_MIN = "user_days_to_read_min"
F_USER_DAYS_TO_READ_MAX = "user_days_to_read_max"

F_BOOK_WANT_COUNT = "book_want_count"
F_BOOK_LAST_WANTED = "book_last_wanted"
F_USER_WANT_GENRE_COUNT = "user_want_genre_count"
F_USER_TOP_WANT_GENRE = "user_top_want_genre"

F_TIMESTAMP_YEAR = "timestamp_year"
F_TIMESTAMP_MONTH = "timestamp_month"
F_TIMESTAMP_DAY = "timestamp_day"
F_TIMESTAMP_DAYOFWEEK = "timestamp_dayofweek"
F_TIMESTAMP_HOUR = "timestamp_hour"
F_TIMESTAMP_WEEKEND = "timestamp_weekend"
F_TIMESTAMP_SEASON = "timestamp_season"
F_DAYS_SINCE_FIRST_ACTIVITY = "days_since_first_activity"
F_DAYS_SINCE_LAST_ACTIVITY = "days_since_last_activity"

F_BOOK_GENDER_MEAN_RATING = "book_gender_mean_rating"
F_BOOK_GENDER_COUNT = "book_gender_count"
F_BOOK_AGE_MEAN_RATING = "book_age_mean_rating"
F_BOOK_AGE_COUNT = "book_age_count"
F_AGE_GROUP = "age_group"